sudo: false
language: ruby

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

matrix:
  fast_finish: true
  include:
    - rvm: 2.6.1
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.1.0.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: 2.5.0
      gemfile: Gemfile
    - rvm: 2.4.1
      gemfile: Gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/default_factory_girl.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rspec33.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rspec34.gemfile
    - rvm: 2.3.1
      gemfile: Gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/activerecord42.gemfile
  allow_failures:
    - rvm: 2.6.1
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.1.0.0
      gemfile: gemfiles/jruby.gemfile
